baseURL = "https://anarchylinux.org/"
theme = "terrassa"
defaultContentLanguage = "en"
language = "en-GB"
enableRobotsTXT = true
title = "Anarchy Linux"
author = "Erazem Kokot"
paginate = 5 # Number of blog posts on one page

[params]
    description = "A simple and intuitive Arch Linux installer"
    favicon = "favicon.ico"
    logo = ""
    
[params.hero]
    textColor = ""

[params.cta] # Call To Action 
    show = true
    cta = "Download"
    link = "https://github.com/deadhead420/anarchy-linux/releases"

[params.separator] # Separators between sections on the home page
    show = true

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = false
    action = "https://formspree.io/contact@erazem.eu"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Message"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "January 2, 2006"

[params.social]
    github = "https://github.com/deadhead420/anarchy-linux"

[params.copy] # Copyright
    copy = "Licensed under the CC-BY-SA-4.0 license" # Empty for default content
